### ISSUE TITLE
[Question] Does Drython allow template metaprogramming?

### ISSUE THREAD

**Issue by phantomcraft** [gilch/drython#1]
Drython has support for [quasiquoted S-expressions](https://github.com/gilch/drython/blob/eb1773c14060e31e2544f5fb69dd31621d0bc291/drython/s_expression.py#L408).

My question is:

Is it possible to do template metaprogramming using Drython?

I'm asking this because there is an article in Wikipedia saying that Common Lisp, Scheme and most lisp dialects has support for it by using quasiquote operators: https://en.wikipedia.org/wiki/Metaprogramming#Template_metaprogramming

**Comment by gilch** [comment]
I think the answer is probably yes, depending on exactly what you mean by that. Python is already duck typed, so it doesn’t need templates for generics.

You may also be interested in my [Hissp repo](https://github.com/gilch/hissp) and its extension [Hebigo](https://github.com/gilch/hebigo) (largely based on techniques from Drython), both of which implement a kind of quasiquote or template quote for metaprogramming Python.

See Hissp’s [macro tutorial](https://hissp.readthedocs.io/en/latest/macro_tutorial.html) (and bundled macro [source](https://github.com/gilch/hissp/blob/master/src/hissp/macros.lissp)) for more on what these systems can do.

**Comment by phantomcraft** [comment]
Thanks, I'll check them and study when I have a spare time.
